### PR TITLE
update to TFLite 2.5.0

### PR DESCRIPTION
**Pull request by phlash**
Works for me, please test using the following and confirm or report issues here:
```bash
$ git checkout main
$ git fetch origin pull/88/head:tflite-2-5-0
$ git checkout tflite-2-5-0
$ make clean all && ./deepseg -d -d -c <your camera> -v <your loopback>
```

### CODE REVIEW

**Comment by BenBE** [comment]
Causes a FTBFS for me:

```bash
$ LC_ALL=C make
g++ tensorflow//tensorflow/lite/tools/make//gen/linux_x86_64/lib//libtensorflow-lite.a deepseg.cc loopback.cc transpose_conv_bias.cc -Ofast -march=native -fno-trapping-math -fassociative-math -funsafe-math-optimizations -Wall -pthread -I tensorflow/ -I tensorflow//tensorflow/lite/tools/make//downloads/absl -I tensorflow//tensorflow/lite/tools/make//downloads/flatbuffers/include -ggdb -I/usr/include/opencv4/opencv -I/usr/include/opencv4 -lrt -ldl -L tensorflow//tensorflow/lite/tools/make//gen/linux_x86_64/lib/ -ltensorflow-lite -ldl -lopencv_stitching -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_highgui -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_quality -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core -o deepseg
/usr/bin/ld: tensorflow//tensorflow/lite/tools/make//gen/linux_x86_64/lib//libtensorflow-lite.a(tensor_utils.o): in function `tflite::tensor_utils::VectorBatchVectorAdd(float const*, int, int, float*)':
tensor_utils.cc:(.text+0x3e5): undefined reference to `tflite::tensor_utils::PortableVectorBatchVectorAdd(float const*, int, int, float*)'
/usr/bin/ld: tensorflow//tensorflow/lite/tools/make//gen/linux_x86_64/lib//libtensorflow-lite.a(tensor_utils.o): in function `tflite::tensor_utils::ReductionSumVector(float const*, float*, int, int)':
tensor_utils.cc:(.text+0x425): undefined reference to `tflite::tensor_utils::PortableReductionSumVector(float const*, float*, int, int)'
/usr/bin/ld: tensorflow//tensorflow/lite/tools/make//gen/linux_x86_64/lib//libtensorflow-lite.a(tensor_utils.o): in function `tflite::tensor_utils::ReductionSumVector(int const*, int*, int, int)':
tensor_utils.cc:(.text+0x435): undefined reference to `tflite::tensor_utils::PortableReductionSumVector(int const*, int*, int, int)'
/usr/bin/ld: tensorflow//tensorflow/lite/tools/make//gen/linux_x86_64/lib//libtensorflow-lite.a(tensor_utils.o): in function `tflite::tensor_utils::ReductionSumVector(signed char const*, int*, int, int)':
tensor_utils.cc:(.text+0x445): undefined reference to `tflite::tensor_utils::PortableReductionSumVector(signed char const*, int*, int, int)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:23: deepseg] Error 1
```

Will have to retry with a clean working copy avoiding any old source artifacts …

**Review by BenBE — APPROVED** [review]

**Comment by phlash** [comment]
Thanks @BenBE, I too had to nuke all the previous tensorflow lite downloads/built objects. CMake seems to be nicer in this regard, as it correctly manages dependent source versions.

**Comment by phlash** [comment]
@floe, can you confirm this works for you - then I'll merge to main and experimental, closing both associated tickets.

**Comment by phlash** [comment]
Just noticed a regression on the part of Google, with v.2.5.0 tensorflow, and a CMake build, we see one of the dependencies (`psimd`) appear in _our source folder_ under `deps/psimd`. I have eventually found a work-around, and need to report back to Google...

**Comment by BenBE** [comment]
What's the effect of this aside from downloading files to the wrong folder?

**Comment by phlash** [comment]
> What's the effect of this aside from downloading files to the wrong folder?

Nothing adverse to the build, but it pollutes our source tree and must be removed along with the `build` folder to clean up.

**Comment by phlash** [comment]
I went to report the regression, and discovered that the XNNPACK and FP16 teams have previously put in a fix, unfortunately the v2.5.0 tagged version of TFLite was created during the month this bug was present, so I'll stick with my workaround until a later version of TFLite where it should be fixed.

**Comment by phlash** [comment]
Looks like we won't see any more test reports coming back, so merging this now

**Pull request merged**
