### PR TITLE
Blur video background

### PR DESCRIPTION
**Pull request by peckto**
Currently the background is replaced by a green screen in case no background image is given.
I thought it would be nice to blur the background of the video stream instead.

Do you have any special use case for the green screen mode?
In this case I can add an extra cli argument for the blur.

### CODE REVIEW

**Comment by BenBE** [comment]
The green screen mode is essentially useful in combination with other software like OBS Studio for further processing as you can use OBS to filter that solid green background and replace it by more complex compositions that deepbacksub itself does not implement.

**Comment by peckto** [comment]
Ok, I see.
I changed the PR to add an extra blur option `-u`.

`-b` is used for the background image. 
Maybe its better to rename this to `-i` and use `-b` for the blur?

**Comment by BenBE** [comment]
What about `-p bgblur:<strength>` (`-p` for "post-processing"), so we could have others.
Also an idea I had was to blur the mask a bit when copying the image over, so the edges of the selected image part aren't that sharp. The radius for this could similarly be set with something like `-p edgeblur:<strength>`.

**Comment by BenBE** [comment]
Moving this to experimental for now, so we can experiment a bit more with this feature.

**Comment by peckto** [comment]
The post-processing option sounds nice. I also thought about an option to dilate the mask, to optimize the clipping result.

I changed the PR to add the ` -p bgblur:<strength>` option.
Unfortunately there is already the `-p` "Show progress bar" option. I renamed this to `-s` for now.

**Comment by peckto** [comment]
I noticed, the experimental branch is behind master. Do you plan to rebase?

**Comment by BenBE** [comment]
Will have to take a look, but IIRC there's nothing special preventing to rebase experimental ATM. Will do in a moment.

**Comment by phlash** [comment]
@peckto, @BenBE polite nudge for this PR, anything we want done before merging to `experimental` ?

**Comment by BenBE** [comment]
@phlash LGTM.

**Pull request merged**
