### PR TITLE
GPU and DOCKER

### PR DESCRIPTION
**Pull request by SamSpiri**
That's @phlash 's gpu integration https://github.com/phlash/backscrub/tree/xnnpack-test
discussed in https://github.com/floe/backscrub/issues/79

Add Dockerfile and docker-compose.yml in order to quickly have everything ready to compile the project.
To try it out: Edit docker-compose.yml to set correct arguments and run `docker-compose up`

Add some more command line arguments
-G to enable GPU
-s to set FPS
-T to set threshold_probability, which was with FIXME comment.
But I didn't notice any change while going from 0.2 to 0.8. Bug?

Accidentally commited the starwars room background.

### CODE REVIEW

**Comment by BenBE** [comment]
Having a Docker file doesn't relief you from documenting step-by-step how to setup a proper environment.

Also the GPU options should only be available with builds that enable GPU support. Having such flags available may be part of some compile option list, or may be shown as `GPU: unavailable` instead of the usual `GPU: yes`/`GPU: no`

**Comment by phlash** [comment]
@SamSpiri thanks for the enthusiasm, glad the GPU hackery worked at all! You might want to break this PR down a bit, there's a quite a lot going on:
 * Shift to CMake builds - we have a PR for that (#50), not sure where that is with avoiding dependency builds on every call, I simply started there and worked out how to turn on other features in a TfLite build.
 * Docker wrapper - might be better as a separate git repo that references backscrub as a sub-project. I'm not sure who would look after Docker stuff in this tree :question: so for now you are likely to retain ownership of this for yourself or others who want a Dockerised build.
   * Docker base image - you've picked Cuda/Nvidia, which is fine if that's what you've got, there will be AMD and possibly others..
 * backscrub code changes - as discussed in #79, and echoing @BenBE comments above, we haven't made any decision to include GPU acceleration in the `main` branch or to build with CMake yet. It's now proven to be possible, but we ought to consider user experience (eg: should there be a graceful fallback if GPU is not usable - right now it crashes out?), and any XNNPACK or GPU support relies on a CMake build which is not officially in yet (although I think this will be 'real soon now' :tm: )

Please be patient with us, as we've yet to arrange an IRL conversation to talk this stuff through :smile:

**Comment by SamSpiri** [comment]
That PR is just a quick share of my progress so far.
I didn't mean to merge in with all that stuff. That's too much for one PR indeed.
I'd wait for the CMake merged in, and than we could base on it for further improvements like XNNPACK and GPU.

I also added background blurring to the mix (only locally yet). Got it from another pull request. And added option to use GPU for blurring. It actually opens the pandora box to do more stuff on gpu. Looking forward - also a mask blending on gpu would be cool.

**Comment by phlash** [comment]
@SamSpiri can this PR be closed? Now we have CMake builds, you should be in a position to submit various individual changes as suggested above...

**Comment by phlash** [comment]
closing due to inactivity

**Pull request closed without merging**
